# Generated by Django 2.2.12 on 2020-04-30 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Projcts',
            new_name='Projects',
        ),
    ]
